### ISSUE TITLE
[Arc Dark Theme] the colors of some search/input box's are overlapping with text color!

### ISSUE THREAD

**Issue by ghost** [horst3180/arc-firefox-theme#108]
On about 15% of the sites I visit, the search bar is either so dark its not visible, or the text is so light (white or light grey) that you cant see what youre typing into the search bar. Im attaching some pictures to show you what I mean.
![screenshot from 2017-03-04 15-58-30](https://cloud.githubusercontent.com/assets/5505269/23582252/64f7d0a4-00f4-11e7-8a45-659b26d9b0c1.png)
![screenshot from 2017-03-04 16-06-52](https://cloud.githubusercontent.com/assets/5505269/23582269/e366b63a-00f4-11e7-8bb5-5473ea549f07.png)

**Comment by arcticicestudio** [comment]
This is because most sites assume that the native system style is a light background with a dark font like in macOS and Windows so they do not explicitly set CSS rules for it, but they have not considered that Linux systems are using GTK themes which can be changed by the user easily.
YouTube/Google on the other hand want a custom style for they search bar styled with JS and CSS.

You can modify your [UserChrome.css](http://kb.mozillazine.org/index.php?title=UserChrome.css&printable=yes) file to explicitly set [styles for specific domains](https://developer.mozilla.org/en-US/docs/Web/CSS/@document) or [globally for all sites](https://wiki.archlinux.org/index.php/firefox#Unreadable_input_fields_with_dark_GTK.2B_themes).
