### ISSUE TITLE
“The addon could not be installed because it does not match the add-on Firefox expected”

### ISSUE THREAD

**Issue by GAumala** [horst3180/arc-firefox-theme#94]
I can't install the theme from https://addons.mozilla.org/en-US/firefox/collections/horst3180/a/ on firefox 49 in arch linux. After download, I get this error “The addon could not be installed because it does not match the add-on Firefox expected”

Also building from source doesn't work. When I drag the .xpi file it says "Arc Theme could not be installed because it is incompatible with Firefox 49.0.1"

**Comment by arcticicestudio** [comment]
![scrot-arc-firefox-theme- 94](https://cloud.githubusercontent.com/assets/7836623/20461536/6415de14-af01-11e6-88c4-58a2d0de00ab.png)

That's why the version information box says

> Works with Firefox 50.0 - *

and the version of the theme starts with a `50`.

You should update to the latest `firefox` package version `50.0-1` via `pacman` and try again.

If you'd like to stay on version `49.x` you should clone the repository, checkout to tag [`49.20160920`](https://github.com/horst3180/arc-firefox-theme/tree/49.20160920) and build it from source again.

**Comment by GAumala** [comment]
I see. Thanks for the quick reply.
